-- Ejecutar esto como usuario SYSTEM si aún no existe el esquema
CREATE USER PROYECTO_DELIVERY IDENTIFIED BY ProyectoDelivery (contraseña);
GRANT CONNECT, RESOURCE, DBA TO PROYECTO_DELIVERY;
-- 1. Crear la secuencia para el ID automático
CREATE SEQUENCE USUARIOS_SEQ 
START WITH 1 
INCREMENT BY 1;

-- 2. Crear la tabla de Usuarios
CREATE TABLE USUARIOS (
    NOMBRE VARCHAR2(50),
    ID_USUARIO NUMBER NOT NULL,
    CORREO VARCHAR2(80) NOT NULL,
    CLAVE VARCHAR2(100) NOT NULL,
    ROL VARCHAR2(20) NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO)
);

-- 3. Crear el Trigger para autoincrementar el ID
CREATE OR REPLACE TRIGGER USUARIOS_TRG 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW 
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
  END IF;
END;
/
