-- Ejecutar esto como usuario SYSTEM si aún no existe el esquema
CREATE USER PROYECTO_DELIVERY IDENTIFIED BY ProyectoDelivery (contraseña);
GRANT CONNECT, RESOURCE, DBA TO PROYECTO_DELIVERY;
-- 1. Crear la secuencia para el ID automático
CREATE SEQUENCE USUARIOS_SEQ 
START WITH 1 
INCREMENT BY 1;

-- 2. Crear la tabla de Usuarios
CREATE TABLE USUARIOS (
    NOMBRE VARCHAR2(50),
    ID_USUARIO NUMBER NOT NULL,
    CORREO VARCHAR2(80) NOT NULL,
    CLAVE VARCHAR2(100) NOT NULL,
    ROL VARCHAR2(20) NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO)
);

-- 3. Crear el Trigger para autoincrementar el ID
CREATE OR REPLACE TRIGGER USUARIOS_TRG 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW 
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
  END IF;
END;
/

-- Creamos la tabla PEDIDOS
CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,      
    ID_REPARTIDOR NUMBER,            
    DESCRIPCION VARCHAR2(200) NOT NULL,
    DIRECCION_ENTREGA VARCHAR2(150) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL, 
    URGENCIA NUMBER NOT NULL,        
    CONSTRAINT PEDIDOS_PK PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT CHK_PEDIDO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'ASIGNADO', 'ENTREGADO')),
    CONSTRAINT CHK_PEDIDO_URGENCIA CHECK (URGENCIA IN (1, 2, 3))
);

-- Creamos los puentes correctos enlazando los IDs de forma exacta
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDO_REPARTIDOR FOREIGN KEY (ID_REPARTIDOR) REFERENCES USUARIOS(ID_USUARIO);

-- Secuencia y el trigger para controlar el ID automático en la base de datos
CREATE SEQUENCE PEDIDOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PEDIDOS_TRG
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_PEDIDO IS NULL THEN
    SELECT PEDIDOS_SEQ.NEXTVAL INTO :NEW.ID_PEDIDO FROM DUAL;
  END IF;
END;
/